/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Asteroids2.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GroupProps } from "@react-three/fiber";

export default function Asteroids2(props: GroupProps) {
  const { nodes, materials } = useGLTF("/Asteroids.glb") as any;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Node.geometry} material={materials.mat15} />
    </group>
  );
}

useGLTF.preload("/Asteroids.glb");
