/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Neptune.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GroupProps } from "@react-three/fiber";

export default function Neptune(props: GroupProps) {
  const { nodes, materials } = useGLTF("/Neptune.glb") as any;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.GeoSphere001_1.geometry}
        material={materials["05___Default"]}
      />
      <mesh
        geometry={nodes.GeoSphere001_1_1.geometry}
        material={materials["04___Default"]}
      />
    </group>
  );
}

useGLTF.preload("/Neptune.glb");
