/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Satellite.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GroupProps } from "@react-three/fiber";

export default function Satellite(props: GroupProps) {
  const { nodes, materials } = useGLTF("/Satellite.glb") as any;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Satellite.geometry} material={materials.Mat} />
    </group>
  );
}

useGLTF.preload("/Satellite.glb");
