/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Saturn.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GroupProps } from "@react-three/fiber";

export default function Saturn(props: GroupProps) {
  const { nodes, materials } = useGLTF("/Saturn.glb") as any;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.group292618952.geometry}
        material={materials.mat15}
      />
      <mesh
        geometry={nodes.group2013386449.geometry}
        material={materials.mat15}
      />
      <mesh
        geometry={nodes.mesh646701568.geometry}
        material={materials.mat15}
      />
      <mesh
        geometry={nodes.mesh646701568_1.geometry}
        material={materials.mat18}
      />
    </group>
  );
}

useGLTF.preload("/Saturn.glb");
